version: "3.7"

services:
  bwhero:
    image: yonle/bwhero:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      LISTEN: 0.0.0.0:8080
      #USER_AGENT: Mozilla/5.0; go-bwhero [https://github.com/Yonle/bwhero]
      #IMAGESIZELIMIT: 50000000
      #ANIMATIONSIZELIMIT: 50000000
      #VIDEOSIZELIMIT: 100000000
